### PR TITLE
toggle revoke button if already answered and revokable is true

### PR DESCRIPTION
**Pull request by albertborsos**
Revoke button is not visible after a page refresh and the widget has an answer.

References to: #177 #244

### CODE REVIEW

**Comment by albertborsos** [comment]
Seriously, check this issue please, it is real.
Check this fiddle. Click to "Got it!" -> tab shows. Refresh the page -> tab is missing.
https://jsfiddle.net/2cf0de51/

**Comment by thexmanxyz** [comment]
@albertborsos I also think we need a fix here. However I'm not really happy with your PR. Your condition does not reflect what we need:

`if (!this.options.enabled && this.options.revokable) {`

it should be something like

`} else if (this.hasAnswered() && this.options.revokable) {`

Because both condition should not met at once so we need an else + `.enabled` is the wrong condition we need `hasAnswered`

**Comment by albertborsos** [comment]
@thexmanxyz Thanks, I think you are right. But after you answered then this snippet sets the `options.enabled` to `false` :) Thats why your solution is not working. (tested)

```
            // returns true if `onComplete` was called
            if (checkCallbackHooks.call(this)) {
                // user has already answered
                this.options.enabled = false;
            }
```

https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L359

**Comment by albertborsos** [comment]
But, I pushed a fixed version. I think the above issue is another ticket :)

**Comment by thexmanxyz** [comment]
@albertborsos You are totally right, sorry mb. Didn't see and neither expect that they set it `enabled = false;` after `hasAnswered` does also logically not really make sense to me that it is handled this way. And yeah you are right that might be another issue.

Your changes look good thanks! Depending on the `.enabled` we could instead also skp the `hasAnswered` but it's ok now. Don't change it anymore. Here just what I meant. But it's fine as it is now.

```
if (!this.hasAnswered() && this.options.enabled) {
        this.open();
      } else if (this.options.revokable) {
        this.toggleRevokeButton(true);
}
```

**Comment by albertborsos** [comment]
I am not sure. There is some extra cases when `.enabled` is `false`, not answered (or answered), but `.revokable` is `true`. So my last version is not too correct :D Because it runs when the previous example occures.

This would be the ultimate function, but this is not working now :)

```
    // opens the popup if no answer has been given
    CookiePopup.prototype.autoOpen = function(options) {
      if(!this.options.enabled){
        return;
      }

      if (!this.hasAnswered()) {
        this.open();
        return;
      }

      if (this.options.revokable) {
        this.toggleRevokeButton(true);
      }
    };
```

**Comment by albertborsos** [comment]
Forget about it :D It tricked me because `.enabled` is incorrectly `false` when answered :D I think it is good enough.

**Comment by thexmanxyz** [comment]
@albertborsos Yes the above would be the ultimate function. It's quite similar to the thing i posted in my first correction. TBH I'm not a fan of returns if you can do it in 5 lines with a nested if / else. However that depends on ones personal favor. Sorry for the late answer.

`.enabled` is just checked in `autoOpen()` and not anywhere else. In the current situation the PR is perfectly fine and can also be a bit more simplified. However `enabled` should be somehow reworked in another PR. From what I saw in the code a clear distinction between `enabled` and `hasAnswered` MUST be made because this isn't actually the case. That's why the logically right checks don't work.

**Comment by zombiefredrik** [comment]
Will this be merged? Need this for GDPR functionality! Patched manually for now, but it's better to have the npm package.

**Comment by albertborsos** [comment]
@alexmorleyfinch please review these changes. Thanks.

**Comment by Ruud68** [comment]
Hi, I can confirm the issue and I can conform that this PR fixes it.
What is needed to get is PR accepted?

**Comment by tjdo** [comment]
agreed. This PR needs to be merged

**Comment by davidsekar** [comment]
I can re-confirm, that this PR fixes the issue. Please merge.

**Comment by axion-mike** [comment]
I think I just submitted a PR with this exact solution. The only thing this lacks is you did not run "gup build" to recompile everything. That would make a new "build/cookieconsent.min.js"

Its crazy this has not already been merged. I went nuts trying to get this to work for the May 25 GDPR deadline.

**Comment by albertborsos** [comment]
Thanks @axion-mike! I did it, but I do not think it is matter since it is a 3 months old PR :D

**Comment by mcdappdev** [comment]
This fix works for me! Would love to see it merged by a contributor/owner

**Comment by Schuer84** [comment]
Why isn't this merged yet?

**Comment by nsrosenqvist** [comment]
Who is the maintainer of this project? This was driving me nuts and the solution was lying here in a 6 month old pull request?!

**Comment by mcdappdev** [comment]
Yeah, no one seems to be particularly active

**Comment by nsrosenqvist** [comment]
@Dolondro ping

**Comment by tjdo** [comment]
The project was developed by someone at Silktide, in the UK. I suggest we all send them a message to release the source to the community ownership or designate someone at the org to maintain the project:
https://silktide.com/about/contact-us/

**Comment by alexmorleyfinch** [comment]
There is news yes, see https://github.com/insites/cookieconsent/issues/409 for details.

Great solution, unfortunately another PR had a solution like this and I merged that one first, sorry.

**Pull request closed without merging**
