### PR TITLE
Add IE8 support

### PR DESCRIPTION
**Pull request by thenickdude**
This PR adds an optional polyfill that users can include to add support for IE8, and makes a couple of small patches to the style handling code to be IE8 compatible.

The examples have also been modified to work properly on IE8.

### CODE REVIEW

**Comment by DanielRuf** [comment]
This should not be part of this library, just part of your individual setups.

**Comment by thenickdude** [comment]
The library requires code changes to become compatible.

**Comment by DanielRuf** [comment]
> The library requires code changes to become compatible.

Not really. You can always use Babel with its plugins and autoprefixer.
Also IE8 is not officially supported anymore and not used (in the enterprise field).

Still, this is a very specific use case for you but not most others and just bloats the entire library without adding much benefit.

**Comment by alexmorleyfinch** [comment]
I agree with @DanielRuf, plus I don't really think we should be [polluting](https://stackoverflow.com/questions/14034180/why-is-extending-native-objects-a-bad-practice) the [prototypes](https://stackoverflow.com/questions/23807805/why-is-mutating-the-prototype-of-an-object-bad-for-performance). Rather the plugin should just implement it's own util functions.

**Pull request closed without merging**
